#!/bin/bash

echo "Struktura katalogów (https://pl.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)"
echo ""
echo "/bin	Podstawowe pliki wykonywalne (ang. binaries) dostępne dla wszystkich użytkowników (np. cat, ls, cp)."
echo "/boot	Pliki programu rozruchowego (np. kernel, initrd)."
echo "/dev	Pliki urządzeń (ang. device; np. /dev/null)."
echo "/etc	Pliki konfiguracyjne."
echo "/home	Katalogi domowe użytkowników (ang. home directory)."
echo "/lib	Biblioteki (ang. libraries) dla programów z katalogów /bin/ i /sbin/."
echo "/mnt	Punkt montowania (ang. mount point) innych niż natywny systemów plików."
echo "/media	Punkty montowań dla nośników wymienialnych (ang. media; np. CD-ROMów) (pojawiło się w FHS-2.3)."
echo "/opt  Opcjonalne aplikacje."
echo "/proc	Wirtualny system plików proc informujący o stanie systemu i poszczególnych procesów, w większości pliki tekstowe (np. uptime, network)."
echo "/root	Katalog domowy użytkownika root."
echo "/sbin	Pliki wykonywalne do zarządzania systemem (ang. system binaries; np. init, route, ifup)."
echo "/tmp	Pliki tymczasowe (ang. temporary files), których stan nie jest gwarantowany po zamknięciu systemu."
echo "/srv  Dane specyficzne dla miejsca (site-specific), które są udostępniane (ang. served) przez system."
echo "/usr	Drugorzędowa hierarchia dla danych (ang. Unix system resources), dane tylko do odczytu."
echo "/var	Pliki często ulegające zmianom (ang. variable files), takie jak: logi, bazy danych, tymczasowe pliki e-mail."