#!/usr/bin/env bash

echo "GNU coreutils (https://pl.wikipedia.org/wiki/GNU_Coreutils)"
echo
echo "Narzędzia plikowe"
echo "chgrp	Zmienia grupę właścicieli plików"
echo "chown	Zmienia właściciela pliku"
echo "chmod	Zmienia prawa dostępu do pliku lub katalogów"
echo "cp	Kopiuje plik lub katalog"
echo "dir	Działa identycznie jak "ls -C -b". (Posortowane pliki są wyświetlane w kolumnach)"
echo "ln	Tworzy dowiązanie do pliku"
echo "ls	Wyświetla pliki w katalogu"
echo "mkdir	Tworzy katalog"
echo "mv	Przesuwa lub zmienia nazwy plików"
echo "rm	Usuwa pliki"
echo "touch	Zmienia czas ostatniego dostępu do pliku"
echo
echo "Narzędzia tekstowe"
echo "cat	Łączy pliki i wypisuje je na standardowe wyjście"
echo "head	Wypisuje początkową część pliku"
echo "nl	Numeruje linie plików"
echo "sort	Sortuje linie plików tekstowych"
echo "tail	Wypisuje końcową część pliku"
echo "wc	Wypisuje liczbę bajtów, słów i linii w plikach"
echo
echo "Narzędzia powłoki"
echo "basename	Oddziela katalog i przyrostek od nazw plików"
echo "chroot	Uruchamia polecenie ze zmienionym katalogiem roota"
echo "date	Wyświetla lub ustawia datę i czas systemowy"
echo "dirname	Usuwa niekatalogowy przyrostek nazwy pliku"
echo "echo	Wyświetla linijkę tekstu"
echo "false	Nic nie robi, zwraca niepowodzenie"
echo "printenv	Wypisuje zmienne środowiskowe"
echo "pwd	Wypisuje nazwę obecnego katalogu roboczego"
echo "sleep	Czeka przez podany czas"
echo "su	Uruchamia powłokę lub komendę z prawami roota"
echo "tee	Czyta ze standardowego wejścia i przesyła kopię na standardowe wyjście oraz do pliku"
echo "true	Nic nie robi, ale zwraca powodzenie"
echo "uname	Wypisuje informacje o systemie"
echo "whoami	Wypisuje efektywny UID"